apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-map
data:
  NODE_ENV: development
  DATABASE_HOST: mysql-0.mysql 
  MYSQL_DATABASE: leaguedb
  MYSQL_USER: nodeapp
  MYSQL_PASSWORD: nodeapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leaguechampions-backend
      tier: backend
  template:
    metadata:
      labels:
        app: leaguechampions-backend
        tier: backend
    spec:
      containers:
      - name: leaguechampions-backend
        image: msalekmouad/leaguechampions-backend:prod
        ports:
            - containerPort: 3000
        envFrom:
          - configMapRef:
              name: backend-map
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: leaguechampions-backend
    tier: backend
  ports:
  - port: 3000
    targetPort: 3000

              