apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-map
data:
  VUE_APP_API_ENDPOINT: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-depl
spec:
  selector:
    matchLabels:
      app: leaguechampions-frontend
  template:
    metadata:
      labels:
        app: leaguechampions-frontend
    spec:
      containers:
      - name: leaguechampions-frontend
        image: msalekmouad/leaguechampions-frontend:prod
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: frontend-map
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: leaguechampions-frontend
  ports:
  - port: 80
    targetPort: 80

        